apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: swiss
    type: Deployment
  name: swiss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiss
      type: Deployment
  template:
    metadata:
      labels:
        app: swiss
        type: Deployment
    spec:
      containers:
        - image: iptizer/swiss
          name: troubleshoot
          imagePullPolicy: Always
          resources: {}
          args:
            # 1 week
            - "sh"
            - "-c"
            - "sleep 604800"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
