apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: swiss
    type: Deployment
  name: swiss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiss
      type: Deployment
  template:
    metadata:
      labels:
        app: swiss
        type: Deployment
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - image: iptizer/swiss
          name: troubleshoot
          imagePullPolicy: Always
          resources: {}
          args:
            - "sleep"
            - "infinity"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
