apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    app: swiss
    type: Deployment
  name: swiss
spec:
  template:
    metadata:
      labels:
        app: swiss
        type: Deployment
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - image: iptizer/swiss
          name: troubleshoot
          imagePullPolicy: Always
          resources: {}
          args:
            # 1 week
            - "sh"
            - "-c"
            - "sleep 5"
      dnsPolicy: ClusterFirst
      restartPolicy: Never
